### ISSUE TITLE
deploy to render is broken

### ISSUE THREAD

**Issue by phishy** [logchimp/deploy-buttons#1]
This URL produces an error.
https://dashboard.render.com/blueprint/new?repo=https%3A%2F%2Fgithub.com%2Flogchimp%2Fdeploy-buttons

`Cannot read properties of undefined (reading 'providerId')`

**Comment by mittalyashu** [comment]
Ah! I just notice you've already created an issue here. Think, I might have missed the notification for this repository.

**Comment by mittalyashu** [comment]
This issue has been resolved in https://github.com/logchimp/deploy-buttons/commit/ccc7bccaa1784687476402177d68cb068584454c

I'm closing this issue for now, please don't hesitate to re-open this issue in case you're facing similar issue again.

**Comment by phishy** [comment]
It's still failing for me, however.

`Nov 20 10:52:41 AM  const ssl = config.database.ssl
Nov 20 10:52:41 AM                              ^
Nov 20 10:52:41 AM  
Nov 20 10:52:41 AM  TypeError: Cannot read property 'ssl' of undefined`

**Comment by mittalyashu** [comment]
@phishy You need to add configuration file to **logchimp-api** service. Please read this section https://logchimp.codecarrot.net/docs/install/render#configuration

**Comment by phishy** [comment]
Ok, thanks!
